databases:
  - name: todo-rails-api-db
    databaseName: todo_rails_api_db_g43w
    user: todo-rails-api
    region: singapore

services:
  - type: web
    name: todo-rails-api
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-rails-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

